set -g @bg0 "#2e3440"
set -g @bg1 "#3b4252"
set -g @bg2 "#434c5e"
set -g @bg3 "#4c566a"
set -g @bg4 "#434c5e"

set -g @fg "#d8dee9"
set -g @red "#bf616a"
set -g @orange "#d08770"
set -g @yellow "#ebcb8b"
set -g @green "#a3be8c"
set -g @aqua "#8fbcbb"
set -g @blue "#88c0d0"
set -g @purple "#b48ead"

set -g @grey0 "#e5e9f0"
set -g @grey1 "#eceff4"
set -g @grey2 "#4c566a"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#4c566a"
set -g pane-active-border-style "fg=#a3be8c"
set -g message-style "fg=#ebcb8b,bg=#3b4252"
set -g clock-mode-colour "#88c0d0"
set -g mode-style "fg=#2e3440,bg=#a3be8c"
