# vim:ft=kitty

## name: Koda Dark Monochrome

foreground              #a6a6a6
background              #080808
selection_foreground    #080808
selection_background    #1a1a1a

cursor                  #a6a6a6
cursor_text_color       #080808

url_color               #707070

active_border_color     #3d3d3d
inactive_border_color   #121212
bell_border_color       #686868

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #080808
active_tab_background   #a6a6a6
inactive_tab_foreground #a6a6a6
inactive_tab_background #121212
tab_bar_background      #080808

mark1_foreground        #080808
mark1_background        #848484
mark2_foreground        #080808
mark2_background        #a6a6a6
mark3_foreground        #080808
mark3_background        #d0d0d0

color0  #000000
color8  #3d3d3d

color1  #4a4a4a
color9  #686868

color2  #5c5c5c
color10 #a6a6a6

color3  #666666
color11 #b0b0b0

color4  #707070
color12 #b8b8b8

color5  #7a7a7a
color13 #d0d0d0

color6  #848484
color14 #c0c0c0

color7  #a6a6a6
color15 #e0e0e0
