# gpg-agent.conf -- Configuración del agente GPG
# Generado por Chezmoi — no editar en $HOME directamente.

# Cachar la contraseña de paso (passphrase) por 8 horas (8 * 3600 = 28800 segundos)
default-cache-ttl 28800
max-cache-ttl 28800
