include colors/colors.conf

# Font
font_family JetBrainsMono Nerd Font Mono
font_size   13.0

# Cursor
cursor_shape          block
cursor_blink_interval 0
cursor_trail          3

# disable_ligatures yes
url_style         curly

# Window layout
remember_window_size    no
initial_window_width    78c
initial_window_height   23c
window_padding_width    20
hide_window_decorations yes
confirm_os_window_close 0

background_opacity            0.90
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0

# Performance & Shell
update_check_interval 0
enable_audio_bell     no
shell_integration     disabled
sync_to_monitor       no
term                  xterm-256color
# --- Mouse & Copy-Paste ---
copy_on_select yes
mouse_map right press ungrabbed paste_from_clipboard

# --- Perf
repaint_delay 8
input_delay   3
