# Font (Optimizada para Starship Cockpit)
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# Cursor
cursor_shape          block
cursor_blink_interval 0

# Window layout
window_padding_width  8
hide_window_decorations yes
confirm_os_window_close 0
background_opacity    1.0

# Performance & Shell
update_check_interval 0
enable_audio_bell     no
term xterm-256color

# --- Theme (Managed by flavours) ---
include colors.conf

