# vim:ft=kitty

## name: Nord
## palette: official

foreground              #d8dee9
background              #2e3440
selection_foreground    #2e3440
selection_background    #4c566a

cursor                  #d8dee9
cursor_text_color       #2e3440

url_color               #a3be8c

active_border_color     #88c0d0
inactive_border_color   #434c5e
bell_border_color       #ebcb8b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #2e3440
active_tab_background   #a3be8c
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252
tab_bar_background      #2e3440

mark1_foreground        #2e3440
mark1_background        #88c0d0
mark2_foreground        #2e3440
mark2_background        #b48ead
mark3_foreground        #2e3440
mark3_background        #8fbcbb

color0  #2e3440
color8  #434c5e

color1  #bf616a
color9  #bf616a

color2  #a3be8c
color10 #a3be8c

color3  #ebcb8b
color11 #ebcb8b

color4  #88c0d0
color12 #88c0d0

color5  #b48ead
color13 #b48ead

color6  #8fbcbb
color14 #8fbcbb

color7  #d8dee9
color15 #e5e9f0
