# vim:ft=kitty

## name: Onedark
## palette: official

foreground              #abb2bf
background              #282c34
selection_foreground    #282c34
selection_background    #3e4451

cursor                  #abb2bf
cursor_text_color       #282c34

url_color               #98c379

active_border_color     #61afef
inactive_border_color   #4b5263
bell_border_color       #e5c07b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #282c34
active_tab_background   #98c379
inactive_tab_foreground #abb2bf
inactive_tab_background #21252b
tab_bar_background      #282c34

mark1_foreground        #282c34
mark1_background        #61afef
mark2_foreground        #282c34
mark2_background        #c678dd
mark3_foreground        #282c34
mark3_background        #56b6c2

color0  #282c34
color8  #4b5263

color1  #e06c75
color9  #e06c75

color2  #98c379
color10 #98c379

color3  #e5c07b
color11 #e5c07b

color4  #61afef
color12 #61afef

color5  #c678dd
color13 #c678dd

color6  #56b6c2
color14 #56b6c2

color7  #abb2bf
color15 #abb2bf
