# vim:ft=kitty

## name: Horizon
## palette: official

foreground              #e0e0e0
background              #1c1e26
selection_foreground    #1c1e26
selection_background    #393c4e

cursor                  #e0e0e0
cursor_text_color       #1c1e26

url_color               #29d398

active_border_color     #26bbd9
inactive_border_color   #474a5e
bell_border_color       #fac39b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #1c1e26
active_tab_background   #29d398
inactive_tab_foreground #e0e0e0
inactive_tab_background #232530
tab_bar_background      #1c1e26

mark1_foreground        #1c1e26
mark1_background        #26bbd9
mark2_foreground        #1c1e26
mark2_background        #ee64ac
mark3_foreground        #1c1e26
mark3_background        #59e1e3

color0  #1c1e26
color8  #474a5e

color1  #e95678
color9  #e95678

color2  #29d398
color10 #29d398

color3  #fac39b
color11 #fac39b

color4  #26bbd9
color12 #26bbd9

color5  #ee64ac
color13 #ee64ac

color6  #59e1e3
color14 #59e1e3

color7  #e0e0e0
color15 #d5d8da
