# vim:ft=kitty

## name: Tokyo-night
## palette: official

foreground              #c0caf5
background              #1a1b26
selection_foreground    #1a1b26
selection_background    #292e42

cursor                  #c0caf5
cursor_text_color       #1a1b26

url_color               #9ece6a

active_border_color     #7aa2f7
inactive_border_color   #414868
bell_border_color       #e0af68

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #1a1b26
active_tab_background   #9ece6a
inactive_tab_foreground #c0caf5
inactive_tab_background #24283b
tab_bar_background      #1a1b26

mark1_foreground        #1a1b26
mark1_background        #7aa2f7
mark2_foreground        #1a1b26
mark2_background        #bb9af7
mark3_foreground        #1a1b26
mark3_background        #73daca

color0  #1a1b26
color8  #414868

color1  #f7768e
color9  #f7768e

color2  #9ece6a
color10 #9ece6a

color3  #e0af68
color11 #e0af68

color4  #7aa2f7
color12 #7aa2f7

color5  #bb9af7
color13 #bb9af7

color6  #73daca
color14 #73daca

color7  #c0caf5
color15 #a9b1d6
