# Kanagawa Dragon Theme for TMUX
# Cohesive with the desktop flat angular design standard

# default statusbar colors
set-option -g status-style "fg=#c5c9c5,bg=#1d1c19"

# default window title colors
set-window-option -g window-status-style "fg=#a6a69c,bg=#1d1c19"

# active window title colors
set-window-option -g window-status-current-style "fg=#181616,bg=#c4746e"

# pane border
set-option -g pane-border-style "fg=#2a2828"
set-option -g pane-active-border-style "fg=#658594"

# message text
set-option -g message-style "fg=#c8c093,bg=#1d1c19"

# pane number display
set-option -g display-panes-active-colour "#658594"
set-option -g display-panes-colour "#2a2828"

# clock
set-window-option -g clock-mode-colour "#658594"

# copy mode highlight
set-window-option -g mode-style "fg=#181616,bg=#658594"

# bell
set-window-option -g window-status-bell-style "fg=#1d1c19,bg=#c4746e"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#c5c9c5,bg=#1d1c19"

# style for command messages
set-option -g message-command-style "fg=#c8c093,bg=#1d1c19"