# =============================================================================
# ~/.config/hypr/conf.d/theme-colors-base.conf
# Tema "home" estático para Hyprland — Kanagawa Dragon
# =============================================================================

general {
    # Gradiente basado en los acentos de la barra Quickshell
    col.active_border = rgba(658594ee) rgba(c4746eee) 45deg
    col.inactive_border = rgba(1c1a1aaa)
}
