# =============================================================================
# input.conf — Configuración de Entrada
# =============================================================================

input {
    kb_layout = us              # Cambiar según tu layout: us, latam, es, etc.
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1            # El foco sigue al cursor
    mouse_refocus = true

    sensitivity = 0             # -1.0 a 1.0, 0 = sin aceleración
    accel_profile = flat        # flat | adaptive (flat recomendado para gaming)

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
        drag_lock = false
    }
}

gesture = 3, horizontal, workspace

cursor {
    no_hardware_cursors = false
    hide_on_key_press = true
}
