# =============================================================================
# ~/.config/hypr/conf.d/theme-colors-base.conf
# Tema "home" estático para Hyprland — Kanagawa Dragon
# =============================================================================

general {
    # Gradiente dinámico utilizando rojo óxido y gris terroso
    col.active_border = rgba(c7362aee) rgba(5a5040ee) 45deg
    col.inactive_border = rgba(080808aa)
}
