# ~/.config/tmux/layouts/minimal.conf
# Layout Minimal - Bloques rectangulares y diseño limpio

# Posición y alineación (Ventanas al centro)
set -g status-position top
set -g status-justify centre

# Colores generales de la barra
set -g status-style "bg=#{@bg0},fg=#{@fg}"

# Estructura del lado Izquierdo: [Sesión]
# - Por defecto: Sesión transparente con texto azul.
# - Con Prefix: Fondo acento, texto oscuro.
# - Sin negrita (bold) para un estilo más fino.
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[bg=#{@accent} fg=#{@bg0}] #{@icon_session}  #S #[default],#[fg=#{@blue}] #{@icon_session}  #S #[default]} "

# Estructura del lado Derecho: [Icono Prefix] [Hora]
set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=#{@accent}] #{@icon_prefix}  #[default],}#[fg=#{@fg},bg=#{@bg0}] %H:%M "

# Formato de Ventanas:
# - Separador: Punto centrado con espacios
# - Inactiva: Número y nombre simples sin fondo.
# - Activa: 
#   * El número (#I) tiene fondo sólido; si la sesión es remota (SSH), muestra el icono al lado del número.
#   * El nombre (#W) va en texto normal sin negrita; si la ventana está en Zoom, muestra el icono en color amarillo.
setw -g window-status-separator "  •  "
setw -g window-status-format "#[fg=#{@fg}] #I #W"
setw -g window-status-current-format "#[bg=#{@accent} fg=#{@bg0}] #I#{?SSH_CONNECTION, #{@icon_ssh},} #[bg=default fg=#{@fg}] #W#{?window_zoomed_flag, #[fg=#{@yellow}]#{@icon_zoom}#[fg=#{@fg}],}"

