set -g @bg0 "#1d2021"
set -g @bg1 "#282828"
set -g @bg2 "#262a2b"
set -g @bg3 "#45403d"
set -g @bg4 "#2f3436"

set -g @fg "#d4be98"
set -g @red "#ea6962"
set -g @orange "#e78a4e"
set -g @yellow "#d8a657"
set -g @green "#a9b665"
set -g @aqua "#89b482"
set -g @blue "#7daea3"
set -g @purple "#d3869b"

set -g @grey0 "#a89984"
set -g @grey1 "#928374"
set -g @grey2 "#7c6f64"

# Semantic accent active
set -g @accent "#{@green}"

# UI COMPONENTS SPECIFIC STYLES
set -g pane-border-style "fg=#45403d"          # bg3
set -g pane-active-border-style "fg=#a9b665"   # green
set -g message-style "fg=#d8a657,bg=#282828"   # yellow sobre bg1
set -g clock-mode-colour "#7daea3"             # blue
set -g mode-style "fg=#1d2021,bg=#a9b665"      # bg0 sobre green
