set -g @bg0 "#181616"
set -g @bg1 "#12120f"
set -g @bg2 "#1d1c19"
set -g @bg3 "#282727"
set -g @bg4 "#393836"

set -g @fg "#c5c9c5"
set -g @red "#c4746e"
set -g @orange "#b6927b"
set -g @yellow "#c4b28a"
set -g @green "#87a987"
set -g @aqua "#8ea4a2"
set -g @blue "#658594"
set -g @purple "#a292a3"

set -g @grey0 "#737c73"
set -g @grey1 "#625e5a"
set -g @grey2 "#4a4744"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#282727"
set -g pane-active-border-style "fg=#87a987"
set -g message-style "fg=#c4b28a,bg=#12120f"
set -g clock-mode-colour "#658594"
set -g mode-style "fg=#181616,bg=#87a987"
