set -g @bg0 "#2b3339"
set -g @bg1 "#323c41"
set -g @bg2 "#3a454a"
set -g @bg3 "#445055"
set -g @bg4 "#4c565a"

set -g @fg "#d3c6aa"
set -g @red "#e67e80"
set -g @orange "#e69875"
set -g @yellow "#dbbc7f"
set -g @green "#a7c080"
set -g @aqua "#83c092"
set -g @blue "#7fbbb3"
set -g @purple "#d699b6"

set -g @grey0 "#9da9a0"
set -g @grey1 "#859289"
set -g @grey2 "#7a8478"

# Semantic accent active
set -g @accent "#{@green}"

# UI COMPONENTS SPECIFIC STYLES
set -g pane-border-style "fg=#445055"          # bg3
set -g pane-active-border-style "fg=#a7c080"   # green
set -g message-style "fg=#dbbc7f,bg=#323c41"   # yellow sobre bg1
set -g clock-mode-colour "#7fbbb3"             # blue
set -g mode-style "fg=#2b3339,bg=#a7c080"      # bg0 sobre green
