set -g @bg0 "#1c1e26"
set -g @bg1 "#232530"
set -g @bg2 "#2e303e"
set -g @bg3 "#393c4e"
set -g @bg4 "#474a5e"

set -g @fg "#e0e0e0"
set -g @red "#e95678"
set -g @orange "#fab795"
set -g @yellow "#fac39b"
set -g @green "#29d398"
set -g @aqua "#59e1e3"
set -g @blue "#26bbd9"
set -g @purple "#ee64ac"

set -g @grey0 "#d5d8da"
set -g @grey1 "#a6accd"
set -g @grey2 "#6c6f93"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#393c4e"
set -g pane-active-border-style "fg=#29d398"
set -g message-style "fg=#fac39b,bg=#232530"
set -g clock-mode-colour "#26bbd9"
set -g mode-style "fg=#1c1e26,bg=#29d398"
