# =============================================================================
# ~/.config/themes/hackerman/hyprland.conf
# Tema estático para Hyprland — Hackerman (Cibernético)
# =============================================================================

general {
    col.active_border = rgba(82FB9Cee) rgba(50f7d4ee) 45deg
    col.inactive_border = rgba(0B0C16aa)
}
