set -g @bg0 "#1a1b26"
set -g @bg1 "#24283b"
set -g @bg2 "#1f2335"
set -g @bg3 "#292e42"
set -g @bg4 "#414868"

set -g @fg "#c0caf5"
set -g @red "#f7768e"
set -g @orange "#ff9e64"
set -g @yellow "#e0af68"
set -g @green "#9ece6a"
set -g @aqua "#73daca"
set -g @blue "#7aa2f7"
set -g @purple "#bb9af7"

set -g @grey0 "#a9b1d6"
set -g @grey1 "#787c99"
set -g @grey2 "#565f89"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#292e42"
set -g pane-active-border-style "fg=#9ece6a"
set -g message-style "fg=#e0af68,bg=#24283b"
set -g clock-mode-colour "#7aa2f7"
set -g mode-style "fg=#1a1b26,bg=#9ece6a"
