# Catppuccin Mocha Tmux Palette
set -g @thm_bg "#1e1e2e"
set -g @thm_fg "#cdd6f4"
set -g @thm_black "#11111b"
set -g @thm_red "#f38ba8"
set -g @thm_green "#a6e3a1"
set -g @thm_yellow "#f9e2af"
set -g @thm_blue "#89b4fa"
set -g @thm_magenta "#cba6f7"
set -g @thm_cyan "#89dceb"
set -g @thm_white "#cdd6f4"
set -g @thm_gray "#585b70"
set -g @thm_accent "#89b4fa"

# Estilos de borde y selección específicos
set -g pane-border-style "fg=#585b70"
set -g pane-active-border-style "fg=#89b4fa"
set -g message-style "fg=#f9e2af,bg=#1e1e2e"
set -g clock-mode-colour "#89b4fa"
set -g mode-style "fg=#1e1e2e,bg=#89b4fa"
