# Kanagawa Dragon Tmux Palette
set -g @thm_bg "#1d1c19"
set -g @thm_fg "#c5c9c5"
set -g @thm_black "#181616"
set -g @thm_red "#c4746e"
set -g @thm_green "#8a9a7b"
set -g @thm_yellow "#c4b28a"
set -g @thm_blue "#658594"
set -g @thm_magenta "#938aa9"
set -g @thm_cyan "#7aa89f"
set -g @thm_white "#c5c9c5"
set -g @thm_gray "#2a2828"
set -g @thm_accent "#c4746e"

# Estilos de borde y selección específicos
set -g pane-border-style "fg=#2a2828"
set -g pane-active-border-style "fg=#658594"
set -g message-style "fg=#c4b28a,bg=#1d1c19"
set -g clock-mode-colour "#658594"
set -g mode-style "fg=#1d1c19,bg=#658594"
