# OneDark Tmux Palette
set -g @thm_bg "#282c34"
set -g @thm_fg "#abb2bf"
set -g @thm_black "#1e2127"
set -g @thm_red "#e06c75"
set -g @thm_green "#98c379"
set -g @thm_yellow "#d19a66"
set -g @thm_blue "#61afef"
set -g @thm_magenta "#c678dd"
set -g @thm_cyan "#56b6c2"
set -g @thm_white "#abb2bf"
set -g @thm_gray "#5c6370"
set -g @thm_accent "#61afef"

# Estilos de borde y selección específicos
set -g pane-border-style "fg=#5c6370"
set -g pane-active-border-style "fg=#61afef"
set -g message-style "fg=#d19a66,bg=#282c34"
set -g clock-mode-colour "#61afef"
set -g mode-style "fg=#282c34,bg=#61afef"
