set -g @bg0 "#191724"
set -g @bg1 "#1f1d2e"
set -g @bg2 "#26233a"
set -g @bg3 "#393552"
set -g @bg4 "#44415a"

set -g @fg "#e0def4"
set -g @red "#eb6f92"
set -g @orange "#f6c177"
set -g @yellow "#ebbcba"
set -g @green "#31748f"
set -g @aqua "#9ccfd8"
set -g @blue "#9ccfd8"
set -g @purple "#c4a7e7"

set -g @grey0 "#908caa"
set -g @grey1 "#6e6a86"
set -g @grey2 "#26233a"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#393552"
set -g pane-active-border-style "fg=#31748f"
set -g message-style "fg=#ebbcba,bg=#1f1d2e"
set -g clock-mode-colour "#9ccfd8"
set -g mode-style "fg=#191724,bg=#31748f"
