# vim:ft=kitty

## name: Kanagawa-dragon
## palette: official

foreground              #c5c9c5
background              #181616
selection_foreground    #181616
selection_background    #282727

cursor                  #c5c9c5
cursor_text_color       #181616

url_color               #87a987

active_border_color     #658594
inactive_border_color   #393836
bell_border_color       #c4b28a

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #181616
active_tab_background   #87a987
inactive_tab_foreground #c5c9c5
inactive_tab_background #12120f
tab_bar_background      #181616

mark1_foreground        #181616
mark1_background        #658594
mark2_foreground        #181616
mark2_background        #a292a3
mark3_foreground        #181616
mark3_background        #8ea4a2

color0  #181616
color8  #393836

color1  #c4746e
color9  #c4746e

color2  #87a987
color10 #87a987

color3  #c4b28a
color11 #c4b28a

color4  #658594
color12 #658594

color5  #a292a3
color13 #a292a3

color6  #8ea4a2
color14 #8ea4a2

color7  #c5c9c5
color15 #737c73
