set -g @bg0 "#282c34"
set -g @bg1 "#21252b"
set -g @bg2 "#1b1d23"
set -g @bg3 "#3e4451"
set -g @bg4 "#4b5263"

set -g @fg "#abb2bf"
set -g @red "#e06c75"
set -g @orange "#d19a66"
set -g @yellow "#e5c07b"
set -g @green "#98c379"
set -g @aqua "#56b6c2"
set -g @blue "#61afef"
set -g @purple "#c678dd"

set -g @grey0 "#abb2bf"
set -g @grey1 "#5c6370"
set -g @grey2 "#4b5263"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#3e4451"
set -g pane-active-border-style "fg=#98c379"
set -g message-style "fg=#e5c07b,bg=#21252b"
set -g clock-mode-colour "#61afef"
set -g mode-style "fg=#282c34,bg=#98c379"
