set -g @bg0 "#1e1e2e"
set -g @bg1 "#181825"
set -g @bg2 "#11111b"
set -g @bg3 "#313244"
set -g @bg4 "#45475a"

set -g @fg "#cdd6f4"
set -g @red "#f38ba8"
set -g @orange "#fab387"
set -g @yellow "#f9e2af"
set -g @green "#a6e3a1"
set -g @aqua "#94e2d5"
set -g @blue "#89b4fa"
set -g @purple "#cba6f7"

set -g @grey0 "#a6adc8"
set -g @grey1 "#bac2de"
set -g @grey2 "#585b70"

set -g @accent "#{@green}"

set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#a6e3a1"
set -g message-style "fg=#f9e2af,bg=#181825"
set -g clock-mode-colour "#89b4fa"
set -g mode-style "fg=#1e1e2e,bg=#a6e3a1"
