# vim:ft=kitty

## name: Rose-pine
## palette: official

foreground              #e0def4
background              #191724
selection_foreground    #191724
selection_background    #393552

cursor                  #e0def4
cursor_text_color       #191724

url_color               #31748f

active_border_color     #9ccfd8
inactive_border_color   #44415a
bell_border_color       #ebbcba

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #191724
active_tab_background   #31748f
inactive_tab_foreground #e0def4
inactive_tab_background #1f1d2e
tab_bar_background      #191724

mark1_foreground        #191724
mark1_background        #9ccfd8
mark2_foreground        #191724
mark2_background        #c4a7e7
mark3_foreground        #191724
mark3_background        #9ccfd8

color0  #191724
color8  #44415a

color1  #eb6f92
color9  #eb6f92

color2  #31748f
color10 #31748f

color3  #ebbcba
color11 #ebbcba

color4  #9ccfd8
color12 #9ccfd8

color5  #c4a7e7
color13 #c4a7e7

color6  #9ccfd8
color14 #9ccfd8

color7  #e0def4
color15 #908caa
