; Gammastep Configuration
[general]
temp-day=6500
temp-night=4000

; Gradual transition
fade=1

; Solar elevation thresholds
; elevation-high=3
; elevation-low=-6

; Custom gamma
; gamma=0.8

; Location provider: manual or geoclue2
location-provider=manual

; Adjustment method: wayland or randr
adjustment-method=wayland

[manual]
; Edit these with your coordinates for auto sunrise/sunset
; You can find them on Google Maps
lat=0.0
lon=0.0
